#!/bin/bash

# Vérifiez si un argument est passé
if [ $# -ne 1 ]; then
  echo "Usage: $0 <user>"
  exit 1
fi

# Stocker l'argument dans une variable
USER=$1

# Exécuter la commande whoami en tant qu'utilisateur spécifié
sudo -u $USER whoami

